# Generated by Django 4.0.5 on 2022-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                ("id_patient", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("cpf", models.DateField(max_length=11)),
                ("birth_date", models.DateTimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("address_number", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "patients",
                "managed": True,
            },
        ),
    ]
