# Generated by Django 4.0.5 on 2022-06-10 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id_book",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("release_year", models.IntegerField()),
                ("state", models.CharField(max_length=50)),
                ("pages", models.IntegerField()),
                ("publishing_company", models.CharField(max_length=50)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
