# Generated by Django 4.0.5 on 2022-06-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='reviews',
        ),
    ]
