# Generated by Django 4.0.5 on 2022-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_options_alter_reviews_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ranking',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
