# Generated by Django 4.0.5 on 2022-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviews_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='approved',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
