# Generated by Django 4.0.5 on 2022-06-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prognostic', models.TextField(blank=True, null=True)),
                ('pain_site', models.CharField(blank=True, max_length=100, null=True)),
                ('pain_type', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('id_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='schedule.schedule')),
            ],
            options={
                'db_table': 'history',
                'managed': True,
            },
        ),
    ]
