# Generated by Django 4.1.1 on 2022-09-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"managed": True},
        ),
        migrations.RenameField(
            model_name="status",
            old_name="Status",
            new_name="name",
        ),
    ]
