# Generated by Django 4.1.1 on 2022-09-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0002_alter_project_options_alter_status_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"managed": True},
        ),
    ]
