# Generated by Django 4.1.1 on 2022-09-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0003_alter_category_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="name",
        ),
    ]
