# Generated by Django 4.1.1 on 2022-09-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban", "0004_remove_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
