# Generated by Django 4.0.5 on 2022-06-17 15:17

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesHistory',
            fields=[
                ('id_image_history', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=images.models.images_history)),
                ('id_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history.history')),
            ],
        ),
    ]
