# Generated by Django 4.1.1 on 2022-09-19 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=70)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "user_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Demand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=250)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "attendant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="helpdesk.support",
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
    ]
