# Generated by Django 4.1.1 on 2022-09-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="demand",
            name="solution",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="demand",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="helpdesk.status",
            ),
        ),
    ]
