# Generated by Django 4.1.1 on 2022-09-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0002_status_demand_solution_demand_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
