# Generated by Django 4.1.1 on 2022-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0003_alter_status_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
