# Generated by Django 4.1.1 on 2022-09-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0004_alter_demand_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="helpdesk.category",
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="attendant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="helpdesk.support",
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="solution",
            field=models.TextField(blank=True, null=True),
        ),
    ]
