# Generated by Django 4.0.5 on 2022-06-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('date_hour', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='patients.patients')),
            ],
            options={
                'db_table': 'schedule',
                'managed': True,
                'unique_together': {('date_hour', 'id_patient')},
            },
        ),
    ]
