# Generated by Django 4.0.5 on 2022-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touristspot',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='touristspot',
            table='tourist_spot',
        ),
    ]
