# Generated by Django 4.0.5 on 2022-06-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_touristspot_options_alter_touristspot_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
