# Generated by Django 4.0.5 on 2022-06-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0003_remove_attraction_id_tourist_spot'),
        ('core', '0003_touristspot_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='attraction',
            field=models.ManyToManyField(to='attraction.attraction'),
        ),
    ]
