# Generated by Django 4.0.5 on 2022-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_options_alter_reviews_table'),
        ('core', '0004_touristspot_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='reviews',
            field=models.ManyToManyField(to='reviews.reviews'),
        ),
    ]
