# Generated by Django 4.0.5 on 2022-06-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_touristspot_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='address',
        ),
    ]
