# Generated by Django 4.0.5 on 2022-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0006_remove_touristspot_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ManyToManyField(to='address.address'),
        ),
    ]
