# Generated by Django 4.0.5 on 2022-06-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0007_touristspot_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='address',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
