# Generated by Django 4.0.5 on 2022-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0003_remove_attraction_id_tourist_spot'),
        ('reviews', '0003_alter_reviews_ranking'),
        ('core', '0009_alter_touristspot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='attraction',
            field=models.ManyToManyField(blank=True, null=True, to='attraction.attraction'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='reviews.reviews'),
        ),
    ]
