# FIELD_NOT_BLANK = "The field {} cannot be left blank."
NOT_FOUND = {"message": "User not found."}
SUCCESS = {"message": "Request made successfully."}
INTERNAL_ERROR = {'message': 'Internal error.'}
PASSWORD_INCORRECT = {'message': 'Password incorrect.'}
USER_CREATED = {'message': 'User created.'}
NOTHING_UPDATE = {'message': 'Nothing to update'}
UPDATE_SUCCESS = {'message': 'Successfully update'}
AUTH_FAILED = {'message': 'Login or password incorrect.'}
LOGGED_SUCCESSFUL = {'message': 'Logged out successfully.'}
LOGGED_OUT = {"message": "You have been logged out."}