# Generated by Django 4.0.5 on 2022-06-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_attraction_id_tourist_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='id_tourist_spot',
        ),
    ]
